PORT=5000

MONGO_HOST=localhost
MONGO_PORT=27017
MONGO_DATABASE=test_api
MONGO_USERNAME=''
MONGO_PASSWORD=''

MAIL_HOST=smtp.gmail.com
MAIL_PORT=587

MAIL_PUBLIC_ME=hvkcbg@gmail.com
PASS_PUBLIC_ME=ngohuusoncbg

MAIL_SEND=hvkcbg1@gmail.com

JWT_SECRET_KEY=
JWT_EXPIRES_TIME=
